In [0]:
import numpy as np
import pandas as pd
from tqdm import trange
import random

In [15]:
ALPHABET = ['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 
            'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V']
print(len(ALPHABET))

20

In [0]:
def gen_fake_data(length):
  seq_list = []
  data_list = []
  for i in trange(length):
    seq = random.choices(ALPHABET, k=7)
    seq_individual = ''.join(seq)
    seq_list.append(seq_individual)
    data_list.append(random.randint(0,100))
  col_list = ['seq', 'num_bounding']
  df = pd.DataFrame(zip(seq_list, data_list), columns=col_list)
  return df

In [22]:
df1 = gen_fake_data(10**6)

100%|██████████| 1000000/1000000 [00:04<00:00, 215903.46it/s]

In [23]:
df1

            seq  num_bounding
0       TGTYQAI            83
1       QHDAPSS             3
2       EMSVYIC            15
3       MWWLHDK            59
4       GWDLKLL            85
5       FWHPRKT            33
6       THVVHMC             9
7       RNNEHFH            63
8       IHIDANL            17
9       LWMQWNA            63
10      PHFAIYM            37
11      SICTIPY            13
12      RHALREE            38
13      TECVWHF            75
14      EEGRSDL             8
15      ESFEYPH             0
16      IGFTCYP            43
17      VYTNAVN            70
18      WVMAFND            37
19      FLRCYMH            83
20      YGRGYDL            12
21      MEEYRHH            58
22      WSHADIG            25
23      DINDIDA            40
24      TQGLEFN            86
25      NSSQPML            38
26      ERGMNCE            85
27      AVLNCIH            51
28      FSIWESG            59
29      YFIMPIN            41
...         ...           ...
999970  HTGKCFP            24
999971  HPGPYEM            44
999972  WAMEPKK            55
999973  CTTITNN            87
999974  PIWAALW            11
999975  MCIDPMA             4
999976  DWCFGCC             3
999977  RGCCFVF            32
999978  DKIMQVI            73
999979  DQYKTYR            47
999980  DNKAIKT            32
999981  QQEGDRE            87
999982  PSICNQC            66
999983  RGETIWL             5
999984  RTPWAMW            29
999985  IVLRKRP            66
999986  CKWGIVM            51
999987  DCYYTLD            38
999988  ICEIMIQ            16
999989  YQDGVAR            61
999990  YGARTHG            82
999991  WHFEKKA            89
999992  KFQMPNN            35
999993  RMHKRVN             3
999994  VAWAKGA           100
999995  PPWSYQG            53
999996  AFHMEGF            30
999997  QEGEGYA            48
999998  HMHTQMM            74
999999  CIEQHIW            54

[1000000 rows x 2 columns]